In [1]:
from fitter import Fitter
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from fitter import get_common_distributions

In [2]:
data = pd.read_excel('AR1.xlsx', skiprows = 1, sheet_name = 'Residuals')

In [3]:
data

,Measles,MR,MMR,TT,Td,DT,DTP,DTP-Hib,Penta,Hexa,IPV,OPV,HPV,HepB,Hib,Rota,PCV
0,-7.558334e+06,-1.886636e+07,-2.099435e+06,-1.224263e+06,-7.815935e+06,1.286034e+06,-1.265615e+06,-1.265615e+06,-8.052736e+06,6731.158321,-4.198003e+06,-5.297968e+05,-5.081063e+05,-1.542804e+07,-1.396719e+06,1.062831e+06,-1.033706e+07
1,-1.233560e+07,-1.895427e+07,-2.323395e+06,2.482965e+05,-8.267753e+06,1.214314e+06,-2.888755e+05,-2.888755e+05,-3.325528e+06,5671.016728,-3.242439e+06,6.553135e+05,-5.231921e+05,2.697691e+07,-1.427613e+06,-1.082775e+07,-1.217868e+07
2,-3.138829e+06,-1.859170e+07,-2.094836e+06,1.049504e+06,-5.192679e+06,8.714782e+05,2.584373e+06,2.584373e+06,-1.208136e+07,-72218.084755,-4.072017e+06,8.793961e+06,-5.047572e+05,1.091856e+06,-1.455520e+06,-5.730492e+05,-4.293852e+06
3,-9.215991e+06,-1.775070e+07,6.159078e+06,1.449712e+06,8.739568e+06,1.175508e+06,2.576244e+06,2.576244e+06,-2.725206e+06,-67277.739592,-4.534779e+06,-8.919478e+06,-4.697217e+05,3.166228e+06,-1.368703e+06,-4.760661e+06,1.806827e+06
4,-4.859693e+06,-4.396891e+06,5.559034e+05,1.014684e+06,-1.457162e+07,1.116534e+06,5.404412e+05,5.404412e+05,-3.551136e+06,-67277.739592,-4.476986e+06,NaN,-4.066500e+05,1.273927e+06,-1.412535e+06,-1.337171e+06,6.060129e+06
5,-6.636863e+06,-1.222524e+07,1.534721e+06,1.650040e+06,-2.594434e+07,3.050467e+06,-2.311911e+06,-2.311911e+06,-8.801125e+06,-67277.739592,-4.539262e+06,NaN,-3.901042e+05,-3.201470e+06,-1.395579e+06,1.588484e+06,1.315633e+07
6,-3.594370e+06,-1.568600e+07,3.199113e+05,4.253517e+06,-1.040253e+07,1.221706e+06,2.253362e+05,2.253362e+05,-1.361246e+06,-67277.739592,-4.423377e+06,NaN,-4.380752e+05,1.528464e+05,1.328451e+07,4.043338e+06,1.173087e+07
7,1.832091e+07,-2.992783e+07,1.187626e+07,3.290280e+06,-2.328726e+07,1.591218e+06,2.855481e+06,2.855481e+06,-6.589082e+06,-67277.739592,-4.484649e+06,NaN,3.850920e+05,1.560521e+07,9.562325e+06,6.586046e+06,6.131031e+06
8,-1.091841e+07,-1.679982e+07,5.227660e+06,4.289033e+06,-6.643737e+06,1.459257e+06,1.661541e+06,1.661541e+06,4.015922e+07,-67277.739592,9.041896e+06,NaN,2.643051e+04,1.529587e+07,1.034981e+07,-7.545758e+05,8.072510e+06
9,1.146396e+07,-1.779623e+07,5.654486e+06,2.529195e+06,-8.474045e+06,8.896636e+05,-2.154656e+06,-2.154656e+06,-1.132668e+07,-67277.739592,2.615026e+07,NaN,3.309655e+06,1.914798e+06,3.936490e+06,-1.145137e+06,-2.376327e+06
10,2.197286e+07,-1.912309e+07,4.359104e+06,3.112015e+07,-4.837911e+06,1.659083e+06,3.205907e+05,3.205907e+05,-7.061004e+06,-67277.739592,-1.579185e+06,NaN,9.837364e+05,5.144709e+07,4.835796e+06,-2.843315e+06,-2.510391e+06
11,-1.498485e+07,-3.489699e+07,-1.634689e+07,1.938801e+07,-5.005663e+06,-1.586382e+07,-9.574417e+04,-9.574417e+04,-1.800590e+05,-67277.739592,5.231644e+06,NaN,-1.464307e+06,-1.668940e+07,-2.270261e+07,9.989772e+06,-1.526138e+07
12,2.209103e+07,-1.032357e+07,-1.217737e+06,2.395566e+07,-4.920902e+05,-4.391250e+05,-8.906052e+04,-8.906052e+04,-4.653726e+06,-67277.739592,7.833700e+06,NaN,NaN,7.843315e+06,-1.519681e+06,1.168946e+07,NaN
13,-1.569935e+07,-1.014789e+07,-3.454038e+06,1.999304e+07,-1.309621e+06,-3.292017e+05,-2.605647e+06,-2.605647e+06,1.123198e+07,-67277.739592,-1.270681e+07,NaN,NaN,4.790168e+06,-1.508688e+06,-1.271827e+07,NaN
14,8.767200e+07,6.026026e+07,4.802009e+06,1.651702e+07,3.753567e+06,-3.713774e+05,-8.990962e+05,-8.990962e+05,4.573150e+07,-52553.189663,NaN,NaN,NaN,-3.991817e+07,-1.534676e+06,NaN,NaN
15,5.460578e+06,-1.555541e+07,-5.721379e+06,-1.519011e+07,3.618034e+07,-4.620356e+05,-8.990962e+05,-8.990962e+05,1.453347e+07,145747.198255,NaN,NaN,NaN,-2.758840e+07,-1.395944e+06,NaN,NaN
16,1.448692e+07,7.136597e+07,-1.987829e+06,4.470594e+07,5.164007e+06,4.578775e+04,-8.990962e+05,-8.990962e+05,-6.989816e+06,-80838.191532,NaN,NaN,NaN,-8.194251e+06,-6.845778e+05,NaN,NaN
17,-2.500899e+07,2.525030e+08,1.961245e+06,-7.163531e+06,1.674326e+07,-3.085555e+05,-8.990962e+05,-8.990962e+05,-3.761684e+06,829007.786724,NaN,NaN,NaN,-5.163125e+06,-7.469739e+05,NaN,NaN
18,-2.431598e+07,-2.419419e+07,-2.836754e+06,-1.114674e+08,8.589561e+07,-3.637962e+05,1.678086e+06,1.678086e+06,-7.676047e+06,35926.443533,NaN,NaN,NaN,-5.760305e+06,-1.929287e+06,NaN,NaN
19,-4.320099e+07,-9.889303e+07,-4.368082e+06,-4.040877e+07,-3.423116e+07,2.556861e+06,-3.419861e+04,-3.419861e+04,-2.351974e+07,-77419.002102,NaN,NaN,NaN,-7.615052e+06,-1.489832e+06,NaN,NaN

In [30]:
dists = get_common_distributions()
dists

['cauchy',
 'chi2',
 'expon',
 'exponpow',
 'gamma',
 'lognorm',
 'norm',
 'powerlaw',
 'rayleigh',
 'uniform']

In [31]:
# Function to bootstrap a single column
def bootstrap_column(column, n=100):
    # Resample with replacement to reach the desired number of samples
    return np.random.choice(column, size=n, replace=True)

# Creating a new DataFrame with bootstrapped columns
bootstrapped_df = pd.DataFrame({col: bootstrap_column(data[col].dropna(), n=100) for col in data.columns})

# Now, bootstrapped_df is your new DataFrame with 100 rows obtained by bootstrapping each column.
bootstrapped_df

,Measles,MR,MMR,TT,Td,DT,DTP,DTP-Hib,Penta,Hexa,IPV,OPV,HPV,HepB,Hib,Rota,PCV
0,-3.594370e+06,-1.032357e+07,-2.099435e+06,2.529195e+06,1.674326e+07,4.578775e+04,2.584373e+06,-2.605647e+06,-6.589082e+06,-67277.739592,-4.539262e+06,6.553135e+05,-5.231921e+05,-2.758840e+07,-6.845778e+05,1.588484e+06,6.131031e+06
1,-4.320099e+07,-3.489699e+07,-2.836754e+06,4.289033e+06,3.753567e+06,3.050467e+06,-2.311911e+06,-8.906052e+04,4.015922e+07,-67277.739592,-4.534779e+06,6.553135e+05,3.850920e+05,1.560521e+07,9.562325e+06,-1.145137e+06,1.806827e+06
2,-1.091841e+07,-2.992783e+07,-2.836754e+06,1.449712e+06,5.164007e+06,-3.637962e+05,-2.311911e+06,-9.574417e+04,-2.725206e+06,-67277.739592,-4.423377e+06,-8.919478e+06,-5.231921e+05,-5.163125e+06,-7.469739e+05,-4.760661e+06,6.131031e+06
3,-1.569935e+07,6.026026e+07,1.534721e+06,1.999304e+07,-2.328726e+07,-3.713774e+05,2.576244e+06,-8.990962e+05,1.123198e+07,145747.198255,-4.423377e+06,-8.919478e+06,-4.066500e+05,1.091856e+06,3.936490e+06,-1.337171e+06,6.060129e+06
4,-9.215991e+06,-1.568600e+07,1.961245e+06,1.938801e+07,-7.815935e+06,1.591218e+06,-9.574417e+04,-3.419861e+04,-1.800590e+05,-80838.191532,5.231644e+06,6.553135e+05,9.837364e+05,-5.760305e+06,-1.455520e+06,-1.082775e+07,-1.033706e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.832091e+07,-1.779623e+07,-2.099435e+06,-7.163531e+06,1.674326e+07,-3.292017e+05,-3.419861e+04,-8.906052e+04,-1.361246e+06,-67277.739592,-4.423377e+06,-5.297968e+05,-5.047572e+05,-5.163125e+06,-1.534676e+06,-1.082775e+07,-2.376327e+06
96,-6.636863e+06,-1.679982e+07,1.961245e+06,-1.519011e+07,-4.920902e+05,1.214314e+06,-9.574417e+04,3.205907e+05,-3.325528e+06,-67277.739592,-4.198003e+06,6.553135e+05,3.850920e+05,1.273927e+06,-1.395944e+06,-2.843315e+06,6.060129e+06
97,8.767200e+07,6.026026e+07,5.654486e+06,2.395566e+07,-1.040253e+07,-4.620356e+05,-2.311911e+06,-8.990962e+05,-8.052736e+06,-67277.739592,2.615026e+07,-5.297968e+05,-3.901042e+05,-5.163125e+06,9.562325e+06,1.588484e+06,6.060129e+06
98,-2.500899e+07,7.136597e+07,4.359104e+06,1.650040e+06,8.589561e+07,-3.713774e+05,-8.990962e+05,2.253362e+05,-4.653726e+06,-67277.739592,-4.423377e+06,-5.297968e+05,3.309655e+06,1.273927e+06,-1.489832e+06,-5.730492e+05,6.060129e+06
99,-7.558334e+06,-3.489699e+07,4.359104e+06,-1.114674e+08,-4.837911e+06,1.591218e+06,-8.990962e+05,2.253362e+05,-6.589082e+06,-67277.739592,-4.539262e+06,-8.919478e+06,-4.697217e+05,1.560521e+07,1.034981e+07,6.586046e+06,6.060129e+06

In [41]:
# Dictionary to store the best fit for each column
# best_fits = {}
fit_results = pd.DataFrame(columns=['Column', 'Best Distribution', 'Parameters', 'Sum Square Error'])


# Iterate over each column in the DataFrame
for column in bootstrapped_df.columns:
    # Use Fitter on the column data
    f = Fitter(bootstrapped_df[column].dropna(), distributions = dists)
    f.fit()
    # Get the best fitting distribution based on sum of square errors
    # best_fits[column] = f.get_best(method = 'sumsquare_error')
    best_fit = f.get_best(method='sumsquare_error')
    
    # Extract the best fitting distribution and its parameters
    best_distribution, params = list(best_fit.items())[0]

    # Extract sum square error for the best fitting distribution
    sse = f.df_errors.loc[best_distribution, 'sumsquare_error']

    # Append results to the DataFrame
    fit_results = fit_results.append({
        'Column': column,
        'Best Distribution': best_distribution,
        'Parameters': params,
        'Sum Square Error': sse
    }, ignore_index=True)
    
#     f.summary()
#     # Access the current figure
#     fig = plt.gcf()  # Get the current figure after calling f.summary()

#     # Dynamically create the file name
#     file_name = f'{column}_distribution_fit_summary.png'

#     # Save the figure with the dynamic file name
#     fig.savefig(file_name)

#     # Close the figure to free memory and avoid overlap in subsequent plots
#     plt.close(fig)

# Print the best fits for each column
best_fits

2024-03-29 10:32:40.359 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:40.407 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:40.410 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:40.864 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:40.936 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:40.975 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:40.985 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:40.995 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:41.045 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:41.064 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:41.110 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:41.144 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:41.171 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:41.174 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:41.650 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:41.650 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:41.705 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:41.705 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:41.753 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:41.817 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:41.853 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:41.934 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:41.950 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:42.272 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:42.331 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:42.428 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:42.453 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:42.497 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:42.602 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
2024-03-29 10:32:42.602 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:42.656 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:42.670 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:42.772 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:42.784 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:42.842 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:43.150 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:43.169 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:43.205 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:43.219 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:43.299 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:43.346 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:43.403 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:43.725 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:43.876 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:43.921 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:43.939 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:43.949 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:43.980 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:43.986 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:44.023 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:44.066 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:44.099 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:44.099 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:44.109 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:44.374 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:44.406 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:44.533 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:44.592 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:44.610 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:44.669 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:44.734 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:44.833 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:45.044 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:45.054 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:45.215 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:45.307 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:45.330 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:45.354 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:45.470 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:45.490 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:45.588 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:45.616 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:46.026 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:46.041 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:46.118 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:46.127 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:46.153 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:46.155 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:46.194 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:46.254 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:46.300 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:46.307 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:46.308 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:46.312 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:46.874 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:46.879 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:46.881 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:46.891 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:46.891 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:46.937 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:46.979 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:47.000 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:47.062 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:47.074 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:47.424 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:47.451 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:47.565 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:47.593 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:47.602 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:47.623 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:47.719 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:47.723 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:47.740 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:47.774 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:47.819 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:48.201 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:48.245 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:48.274 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:48.300 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:48.381 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:48.453 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:48.491 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:48.514 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:48.561 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:48.927 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:49.021 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:49.031 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:49.035 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:49.061 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:49.137 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:49.191 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:49.249 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted norm distribution with error=0.0)
2024-03-29 10:32:49.264 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:49.268 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:49.281 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:49.694 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)
2024-03-29 10:32:49.795 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted exponpow distribution with error=0.0)
2024-03-29 10:32:49.801 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted chi2 distribution with error=0.0)
2024-03-29 10:32:49.809 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted gamma distribution with error=0.0)
2024-03-29 10:32:49.925 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted lognorm distribution with error=0.0)
C:\Users\nicho\AppData\Local\Temp\ipykernel_16100\4175846406.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fit_results = fit_results.append({
2024-03-29 10:32:49.966 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted expon distribution with error=0.0)
2024-03-29 10:32:50.029 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted rayleigh distribution with error=0.0)
2024-03-29 10:32:50.039 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted uniform distribution with error=0.0)
2024-03-29 10:32:50.482 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted cauchy distribution with error=0.0)
2024-03-29 10:32:50.568 | INFO     | fitter.fitter:_fit_single_distribution:337 - Fitted powerlaw distribution with error=0.0)

{'Measles': {'cauchy': {'loc': -5652112.703521139,
   'scale': 9211981.222445093}},
 'MR': {'cauchy': {'loc': -17508678.53547068, 'scale': 4579194.808758552}},
 'MMR': {'norm': {'loc': 235307.34884107544, 'scale': 5808530.764382503}},
 'TT': {'cauchy': {'loc': 2099280.954703667, 'scale': 4449839.172403239}},
 'Td': {'cauchy': {'loc': -5296779.460061355, 'scale': 6059253.1941792555}},
 'DT': {'cauchy': {'loc': 797600.8099725128, 'scale': 791223.0895320121}},
 'DTP': {'cauchy': {'loc': -212588.0061676713, 'scale': 840449.0829257511}},
 'DTP-Hib': {'cauchy': {'loc': -279886.2734512227, 'scale': 717341.94570784}},
 'Penta': {'cauchy': {'loc': -4696424.339975908, 'scale': 3288672.902757018}},
 'Hexa': {'lognorm': {'s': 1.491866919246203,
   'loc': -81654.6281292841,
   'scale': 23970.44987216328}},
 'IPV': {'cauchy': {'loc': -4357924.999859333, 'scale': 488231.6601587646}},
 'OPV': {'cauchy': {'loc': 134386.31361874143, 'scale': 1085637.756423486}},
 'HPV': {'cauchy': {'loc': -444942.6791717428, 'scale': 105315.57715103567}},
 'HepB': {'cauchy': {'loc': -1471110.0313526231, 'scale': 8354819.067990221}},
 'Hib': {'cauchy': {'loc': -1434680.873365813, 'scale': 157423.17392819963}},
 'Rota': {'cauchy': {'loc': -843131.944528593, 'scale': 2559720.5430776626}},
 'PCV': {'uniform': {'loc': -15261377.61749506, 'scale': 28417703.07556697}}}

In [43]:
fit_results.to_excel('residual_distributions.xlsx')