In [2]:
import pandas as pd
import numpy as np


# Load the CSV file to see its content
file_path = 'data/production_capacity_scenarios.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to understand its structure
df.head()

     manufacturer  ...                                           capacity
0     AJ_Vaccines  ...  [7711003.0, 7711003.0, 7711003.0, 7711003.0, 7...
1        BB_NCIPD  ...  [39223956.0, 39223956.0, 39223956.0, 39223956....
2  Bharat_Biotech  ...  [61029105.0, 61029105.0, 61029105.0, 61029105....
3       Bilthoven  ...  [12048153.0, 12048153.0, 12048153.0, 12048153....
4    Biological_E  ...  [164885690.0, 164885690.0, 164885690.0, 164885...

[5 rows x 4 columns]

In [3]:
# Function to apply a random +/- 2% modification to the capacity values
def modify_capacity(capacity_list):
    modified_list = [
        value * (1 + np.random.uniform(-0.02, 0.02)) for value in capacity_list
    ]
    return modified_list

# Apply the modification to every entry in the 'capacity' column
df['capacity'] = df['capacity'].apply(lambda x: modify_capacity(eval(x)))

# Display the first few rows of the DataFrame to understand its structure
df.head()

     manufacturer  ...                                           capacity
0     AJ_Vaccines  ...  [7781485.890546864, 7714975.836374469, 7619528...
1        BB_NCIPD  ...  [38542727.040905595, 38471856.81965083, 399797...
2  Bharat_Biotech  ...  [61381691.975799516, 60933951.778160006, 61075...
3       Bilthoven  ...  [12237487.32895902, 11987906.42107039, 1202627...
4    Biological_E  ...  [163861854.61289003, 163611638.65832192, 16161...

[5 rows x 4 columns]

In [5]:
excel_file_path = 'C:/Users/nicho/OneDrive/Desktop/Vaccine_Tender/L-shaped/Final_codes/data_generation_codes/data/production_capacity_scenarios2.xlsx'
df.to_excel(excel_file_path, index=False)